#!/bin/bash
# INPUT example file: CX20_n5_mapq30_sorted.bam
# OUTPUT example file: CX20_n5_mapq30_sorted_qual30.count

REF=$1 # reference genome (same as the one used for mapping the sequencing reads)
BAM_DIR=$2 # BAM directory containg filtered bam files to be analyzed
WORK_DIR=$3 # Working directory: where to output the counts generated by samtools mpileup and mpileup_count.py
mismatch=$4 # number of mismatches allowed when mapping sequences (only for naming convention - argument can be removed)
N=$5 # Sample number
QUAL=$6 # skip bases with baseQ/BAQ smaller than INT
count_SCRIPT=./Get_variations/mpileup_count.py # UPDATE PATH IF NECESSARY
DEPTH=1000000 # max per-BAM depth to avoid excessive memory usage

samtools mpileup -d $DEPTH -Q $QUAL -BAf $REF $BAM_DIR/CX${N}_n${mismatch}_mapq30_sorted.bam>$WORK_DIR/CX${N}_n${mismatch}_mapq30_sorted_qual${QUAL}.mpileup
python $count_SCRIPT $WORK_DIR/CX${N}_n${mismatch}_mapq30_sorted_qual${QUAL}.mpileup > $WORK_DIR/CX${N}_n${mismatch}_mapq30_sorted_qual${QUAL}.count
